In [1]:
import pandas as pd

In [2]:
ex=pd.read_excel('events/cf25dat.xlsx')

In [3]:
ex['Title']=ex['Title'].str.upper()

In [4]:
ex.to_excel('cf25dat.xlsx')

In [5]:
gx=pd.read_csv('20250623 - Detailed Schedule - v10.csv')

/var/folders/rs/m2cwbt951nlfsrncdqwyny5h0000gn/T/ipykernel_89471/4201498827.py:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15) have mixed types. Specify dtype option on import or set low_memory=False.
  gx=pd.read_csv('20250623 - Detailed Schedule - v10.csv')

In [6]:
g=gx.dropna(subset=['EasyChair'])

In [7]:
g['Date']=g['FILTER OPTIONS.1']
g[['Date','Time','session code']]

/var/folders/rs/m2cwbt951nlfsrncdqwyny5h0000gn/T/ipykernel_89471/952130898.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g['Date']=g['FILTER OPTIONS.1']

       Date           Time session code
12   7/2/25  11:25 - 11:40         S-S1
13   7/2/25  11:40 - 11:55         S-S1
14   7/2/25  11:55 - 12:10         S-S1
19   7/2/25  13:10 - 13:20         P-A1
20   7/2/25  13:20 - 13:30         P-A1
..      ...            ...          ...
153  7/4/25  15:30 - 15:50           CI
154  7/4/25  15:50 - 16:10           CI
155  7/4/25  16:10 - 16:30           CI
156  7/4/25  16:30 - 16:50           CI
157  7/4/25  16:50 - 17:10           CI

[88 rows x 3 columns]

In [8]:
# df=g

# # --- 0) your original df has columns: Date, Time, session code

# # --- 1) drop any rows where Time, Date or code is missing
# df = df.dropna(subset=['Time','Date','session code'])

# # --- 2) pull out exactly two HH:MM groups (as strings)
# df[['start','end']] = df['Time'].str.extract(
#     r'(\d{1,2}:\d{2})\s*-\s*(\d{1,2}:\d{2})'
# )

# # --- 3) drop rows where extract failed (you’ll now have only pure strings)
# df = df.dropna(subset=['start','end'])

# # --- 4) if you want to enforce two-digit hours, parse & re-format;
# #     otherwise you can skip to step 5.
# df['start'] = (
#     pd.to_datetime(df['start'], format='%H:%M', errors='coerce')
#       .dt.strftime('%H:%M')
# )
# df['end'] = (
#     pd.to_datetime(df['end'],   format='%H:%M', errors='coerce')
#       .dt.strftime('%H:%M')
# )
# # drop any rows that still failed parsing
# df = df.dropna(subset=['start','end'])

# # --- 5) group by code (and date), taking earliest start & latest end
# span = (
#     df
#     .groupby(['session code','Date'], as_index=False)
#     .agg(
#         start=('start','min'),
#         end  =('end',  'max')
#     )
# )

# # --- 6) build your dict: code → "YYYY-MM-DD HH:MM - HH:MM"
# result = {
#     row['session code']:
#       f"{row['Date'].date()} {row['start']} - {row['end']}"
#     for _, row in span.iterrows()
# }

# print(result)

In [9]:
absin=pd.read_csv('CAADFutures_abstractin.csv')

In [10]:
trt=absin[absin['#']==27]

In [11]:
putabs=dict(zip(absin['#'],absin['Abstract']))

In [65]:
g['Date']=g['FILTER OPTIONS.1']

/var/folders/rs/m2cwbt951nlfsrncdqwyny5h0000gn/T/ipykernel_89159/1342371881.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g['Date']=g['FILTER OPTIONS.1']

In [14]:
topicmape=dict(zip(g['EasyChair'],g['session title']))
sessimape=dict(zip(g['EasyChair'],g['session code']))

In [15]:
timemape=dict(zip(g['EasyChair'],g['Time']))

In [16]:
idex=ex['ID'].unique()

In [17]:
g['EasyChair']=g['EasyChair'].astype(str).replace('[','').str.replace(']','').str.strip().str.replace('[','')

/var/folders/rs/m2cwbt951nlfsrncdqwyny5h0000gn/T/ipykernel_89471/75282077.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g['EasyChair']=g['EasyChair'].astype(str).replace('[','').str.replace(']','').str.strip().str.replace('[','')

In [18]:
g['EasyChair']=g['EasyChair'].astype(int)

/var/folders/rs/m2cwbt951nlfsrncdqwyny5h0000gn/T/ipykernel_89471/705830128.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  g['EasyChair']=g['EasyChair'].astype(int)

In [19]:
# g['EasyChair']

In [20]:
datemape=dict(zip(g['EasyChair'],g['Date']))
timemape=dict(zip(g['EasyChair'],g['Time']))

In [21]:
topicmape=dict(zip(g['EasyChair'],g['session title']))
sessimape=dict(zip(g['EasyChair'],g['session code']))

In [22]:
[c for c in g['EasyChair'].unique() if c not in idex]

[]

In [23]:
[c for c in idex if c not in g['EasyChair'].unique()]

[]

In [24]:
ex=ex.loc[~ex['ID'].isin([214, 376, 283, 27])]

In [25]:
en=ex[['ID','Title','Authors','Final Topic','Session','Abstract']]
en.reset_index(inplace=True)

In [96]:
# trt

In [30]:
g['EasyChair']

12     238
13     349
14      36
19       5
20      46
      ...
153    330
154    389
155    427
156    445
157    458
Name: EasyChair, Length: 88, dtype: int64

In [31]:
# #One-off 27 to be added. 

en.loc[88,'ID']=27
en.loc[88,'Title']=trt['Title'].values[0]
en.loc[88,'Authors']=trt['Authors'].values[0]
en.loc[88,'Abstract']=trt['Abstract'].values[0]

/var/folders/rs/m2cwbt951nlfsrncdqwyny5h0000gn/T/ipykernel_89471/2216555764.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  en.loc[88,'ID']=27

In [32]:
en

,index,ID,Title,Authors,Final Topic,Session,Abstract
0,0.0,403.0,TEXT-TO-SIHEYUAN: LLM-BASED MULTI-AGENT PROCED...,"Zixi Zhang, Wenshuo Zhang and Runjia Tian",PROMPTING ARCHITECTURE,S-S4,Rule-Based Procedural Content Generation (PCG)...
1,1.0,114.0,CONSTRUCTGNN: A GRAPH NEURAL NETWORK FRAMEWORK...,"Quan Zhou, Yize Li, Zejian Li and Immanuel Koh",ARCHITECTURAL COMPUTING & REASONING,S-S5,"This study proposes a workflow, ConStructGNN, ..."
2,2.0,238.0,DESIGN VALIDATION FOR ROBOTIC FABRICATION: A M...,Pok Yin Victor Leung and Yijiang Huang,INTELLIGENT ROBOTIC ASSEMBLY,S-S1,The use of robotics in construction offers tra...
3,3.0,231.0,READING BETWEEN THE LINES: BRIDGING AI AND ARC...,"Marija Mateljan, Seyran Khademi and Georg Vrac...",ARCHITECTURAL COMPUTING & REASONING,S-S5,Architectural drawings are powerful tools for ...
4,4.0,444.0,INTERACTIVE BIM MODELLING ASSISTANT WITH MULTI...,"Chao Tang, Kam-Ming Mark Tam and Christiane Ma...",PROMPTING ARCHITECTURE,S-S4,The integration of Geographic Information Syst...
...,...,...,...,...,...,...,...
82,82.0,389.0,(CI) AUGMENTATION IN DESIGN AND FABRICATION: E...,"Igor Pantic, Soomeen Hahm, Peter Búš and Zhiyo...",CATALYTIC INTERFACE,CI,The future of architectural practice is increa...
83,83.0,427.0,TOWARD AIXR: DESIGNING A FRAMEWORK FOR AI-INFO...,"Matias del Campo, Joseph Kenny, Eleni Vasiliki...",CATALYTIC INTERFACE,CI,"This paper presents AIXR, a framework for arti..."
84,84.0,445.0,BUILDINGS AS SYMBIOTIC SYSTEMS: CYBERNETIC ADA...,"Davide Schaumann, Andrew Vande Moere, Yuval Ka...",CATALYTIC INTERFACE,CI,Contemporary architectural design increasingly...
85,85.0,458.0,CATALYTIC DESIGN INTERFACES: AI-GUIDED BUILDIN...,"Tejas Chavan, Houssame E. Hsain, Camiel Weijen...",CATALYTIC INTERFACE,CI,"This paper presents HIKARI, a working prototyp..."
88,NaN,27.0,A Full-Process Digital Method for Recursive Ge...,"Shenzhou Dai, Sihang Liu, Haojun Wang, Yulin C...",NaN,NaN,"The commercial wood processing industry, drive..."

In [95]:
# sessimape['27']

In [33]:
en.loc[88,'Session']=sessimape[27]
en.loc[88,'Final Topic']=topicmape[27]

In [34]:
en.tail(3)

,index,ID,Title,Authors,Final Topic,Session,Abstract
84,84.0,445.0,BUILDINGS AS SYMBIOTIC SYSTEMS: CYBERNETIC ADA...,"Davide Schaumann, Andrew Vande Moere, Yuval Ka...",CATALYTIC INTERFACE,CI,Contemporary architectural design increasingly...
85,85.0,458.0,CATALYTIC DESIGN INTERFACES: AI-GUIDED BUILDIN...,"Tejas Chavan, Houssame E. Hsain, Camiel Weijen...",CATALYTIC INTERFACE,CI,"This paper presents HIKARI, a working prototyp..."
88,NaN,27.0,A Full-Process Digital Method for Recursive Ge...,"Shenzhou Dai, Sihang Liu, Haojun Wang, Yulin C...","STRUCTURAL, FABRICATION & MATERIAL LOGIC",P-B2,"The commercial wood processing industry, drive..."

In [129]:
# absin.loc[absin['#']==457]

In [130]:
# en.head(2)

In [131]:
# topicmape[238]

In [94]:
# ct=81
# for i in [457, 82, 330, 389, 427, 445, 458]:
#     try:
#         id,aut,title,subs,typesub,timesub,abs=absin.loc[absin['#']==i].values[0]
#         en.loc[ct]=ct+4,id,title,aut,topicmape[i],sessimape[i],abs
#     except:
#         print(i)
#         tnt=g[g['EasyChair']==i]
#         en.loc[87]=87+4,tnt['EasyChair'].values[0],tnt['title'].values[0],tnt['authors'].values[0],tnt['session title'].values[0],tnt['session code'].values[0],None
#     ct +=1

In [36]:
en['Session']=en['ID'].map(sessimape)

In [37]:
# en.loc[en['Final Topic'].isna(),'Final Topic']='Catalytic Interface'
# # en.loc[en.tail(6).index,'Final Topic']='Catalyi

In [38]:
p2drop=[c for c in idex if c not in g['EasyChair'].unique()]

In [39]:
en.shape

(87, 9)

In [40]:
en['Date']=en['ID'].map(datemape)
en['Time']=en['ID'].map(timemape)

In [41]:
en.loc[~en['ID'].isin(p2drop)].to_excel('events/cf25dat.xlsx')

In [42]:
en

,index,ID,Title,Authors,Final Topic,Session,Abstract,Date,Time
0,0.0,403.0,TEXT-TO-SIHEYUAN: LLM-BASED MULTI-AGENT PROCED...,"Zixi Zhang, Wenshuo Zhang and Runjia Tian",PROMPTING ARCHITECTURE,S-S4,Rule-Based Procedural Content Generation (PCG)...,7/4/25,10:50 - 11:05
1,1.0,114.0,CONSTRUCTGNN: A GRAPH NEURAL NETWORK FRAMEWORK...,"Quan Zhou, Yize Li, Zejian Li and Immanuel Koh",ARCHITECTURAL COMPUTING & REASONING,S-S5,"This study proposes a workflow, ConStructGNN, ...",7/4/25,13:45 - 14:00
2,2.0,238.0,DESIGN VALIDATION FOR ROBOTIC FABRICATION: A M...,Pok Yin Victor Leung and Yijiang Huang,INTELLIGENT ROBOTIC ASSEMBLY,S-S1,The use of robotics in construction offers tra...,7/2/25,11:25 - 11:40
3,3.0,231.0,READING BETWEEN THE LINES: BRIDGING AI AND ARC...,"Marija Mateljan, Seyran Khademi and Georg Vrac...",ARCHITECTURAL COMPUTING & REASONING,S-S5,Architectural drawings are powerful tools for ...,7/4/25,14:00 - 14:15
4,4.0,444.0,INTERACTIVE BIM MODELLING ASSISTANT WITH MULTI...,"Chao Tang, Kam-Ming Mark Tam and Christiane Ma...",PROMPTING ARCHITECTURE,S-S4,The integration of Geographic Information Syst...,7/4/25,10:35 - 10:50
...,...,...,...,...,...,...,...,...,...
82,82.0,389.0,(CI) AUGMENTATION IN DESIGN AND FABRICATION: E...,"Igor Pantic, Soomeen Hahm, Peter Búš and Zhiyo...",CATALYTIC INTERFACE,CI,The future of architectural practice is increa...,7/4/25,15:50 - 16:10
83,83.0,427.0,TOWARD AIXR: DESIGNING A FRAMEWORK FOR AI-INFO...,"Matias del Campo, Joseph Kenny, Eleni Vasiliki...",CATALYTIC INTERFACE,CI,"This paper presents AIXR, a framework for arti...",7/4/25,16:10 - 16:30
84,84.0,445.0,BUILDINGS AS SYMBIOTIC SYSTEMS: CYBERNETIC ADA...,"Davide Schaumann, Andrew Vande Moere, Yuval Ka...",CATALYTIC INTERFACE,CI,Contemporary architectural design increasingly...,7/4/25,16:30 - 16:50
85,85.0,458.0,CATALYTIC DESIGN INTERFACES: AI-GUIDED BUILDIN...,"Tejas Chavan, Houssame E. Hsain, Camiel Weijen...",CATALYTIC INTERFACE,CI,"This paper presents HIKARI, a working prototyp...",7/4/25,16:50 - 17:10
88,NaN,27.0,A Full-Process Digital Method for Recursive Ge...,"Shenzhou Dai, Sihang Liu, Haojun Wang, Yulin C...","STRUCTURAL, FABRICATION & MATERIAL LOGIC",P-B2,"The commercial wood processing industry, drive...",7/3/25,13:25 - 13:35

In [139]:
# en.loc[87,'Abstract']=putabs[458]

In [140]:
# putabs[458]

In [141]:
# tnt=g[g['EasyChair']==458]
# en.loc[87]=87+4,tnt['EasyChair'],tnt['title'],tnt['a

In [63]:
tn=absin.loc[absin['#']==i].values

In [65]:
tn[0][0]

457

In [97]:
g[g['EasyChair']==i].values

array([['Catalytic Interfaces', '7/4/2025', '16:50 - 17:10', 'CI',
        'Catalytic Interfaces Presentation', nan,
        'CATALYTIC DESIGN INTERFACES: AI-GUIDED BUILDING MASSING AND AUTOMATED COMPLIANCE\n',
        'Tejas Chavan, Houssame E. Hsain, Camiel Weijenberg and Sayjel V. Patel',
        458, nan, nan, '16:50 - 17:10', '[ 458 ]',
        'CATALYTIC DESIGN INTERFACES: AI-GUIDED BUILDING MASSING AND AUTOMATED COMPLIANCE\nBy Tejas Chavan, Houssame E. Hsain, Camiel Weijenberg and Sayjel V. Patel',
        nan, nan, '7/4/2025']], dtype=object)

In [104]:
tnt['EasyChair'].values[0]

458

In [17]:
ex['Date']=ex['ID'].map(datemape)
ex['Time']=ex['ID'].map(timemape)

In [19]:
ex['Session']=ex['ID'].map(sessimape)

In [21]:
ex.to_excel('events/cf25dat.xlsx')